# -*- mode: ruby -*-
# vi: set ft=ruby :
# baseado ipt_cloud_course_w8
Vagrant.configure("2") do |config|
  # Docker Swarm nodes
  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "bento/ubuntu-22.04"
      node.vm.network "private_network", ip: "192.168.46.1#{i}"
      node.vm.hostname = "node#{i}"
      node.vm.provider "virtualbox" do |vb|
        vb.name = "Swarm node #{i}"
        vb.memory = "2048"
        vb.cpus = 2
        # create a master VM before creating the linked clones
        vb.linked_clone = true
      end

      node.vm.provision "shell", inline: <<-SHELL
        apt-get update

        # Install Docker - https://docs.docker.com/engine/install/ubuntu/
        for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done
        # Add Docker's official GPG key:
        sudo apt-get update
        sudo apt-get install ca-certificates curl
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc

        # Add the repository to Apt sources:
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update

        # Install latest version
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

        # Uso docker without sudo for the vagrant user
        usermod -aG docker vagrant

        # Initialize Docker Swarm on the master node
        if [ "#{i}" == "1" ]; then
          docker swarm init --advertise-addr 192.168.46.1#{i}
          SWARM_JOIN=$(docker swarm join-token -q worker)
          echo ${SWARM_JOIN} > /vagrant/swarm_join_token.txt
        fi

        # Test docker
        docker run hello-world
        SHELL

        # Provisioning for worker nodes to join the swarm
        if i > 1
          node.vm.provision "shell", inline: <<-SHELL
          SWARM_JOIN=$(cat /vagrant/swarm_join_token.txt)
          docker swarm join --token ${SWARM_JOIN} 192.168.46.11:2377
        SHELL
      end
    end
  end
  # Sync folder for compose.yml
  config.vm.synced_folder "./shared", "/home/vagrant/shared"
end
