version: '3.8'

services:
  web:
    image: aluno25647/ipt-cloud-web:V1.12
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
    networks:
      - app-network

  ws:
    image: aluno25647/ipt-cloud-ws:V1.12
    ports:
      - "8000:8000"
    networks:
      - app-network

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./provision/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
